### PR TITLE
Update hotBAR.php

### PR DESCRIPTION
**Pull request by Erkam246**

### CODE REVIEW

**Comment by FaigerSYS** [comment]
Needlessly. And why u remove sendTip()? :\

**Comment by Erkam246** [comment]
Tip not exist more...

**Comment by FaigerSYS** [comment]
@erkam2002 , ummmm, 'tip' exists in MCPE 0.15.0...... So you're wrong :\

**Comment by Erkam246** [comment]
Oh .... cool xD 0.14.3 was it removed

**Pull request closed without merging**
